=== themetalone/WS1617-Masterarbeit/Simulation/PS-Utils/src/main/resources/configurator/xsd/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://github.com/themetalone/simpleconfig" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:scfg="http://github.com/themetalone/simpleconfig">




    <element name="simulation" type="scfg:simulationType"></element>

    <complexType name="simulationType">
      <sequence>
        <element name="populationen" type="scfg:populationenType"></element>
        <element name="routen" type="scfg:routenType"></element>
      </sequence>
      <attribute name="datenbank" type="string" use="required"></attribute>
      <attribute name="batchgroesse" type="int" use="required"></attribute>
      <attribute name="zeit" type="int" use="required"></attribute>
      <attribute name="krankheit" type="float" use="required"></attribute>
    </complexType>

    <complexType name="populationenType">
      <sequence>
            <element name="standard" type="scfg:populationType" maxOccurs="1" minOccurs="1"></element>
            <element name="population" type="scfg:populationType" maxOccurs="unbounded" minOccurs="1"></element>
      </sequence>
    </complexType>

    <complexType name="populationType">
      <sequence>
        <element name="subpopulation" type="scfg:subpopulationType" maxOccurs="unbounded" minOccurs="0"></element>
        <element name="uebergang" type="scfg:uebergangType" maxOccurs="unbounded" minOccurs="0"></element>
      </sequence>
      <attribute name="name" type="string" use="required"></attribute>
      <attribute name="lebensstandard" type="float" use="required"></attribute>
      <attribute name="migrationsanteil" type="float" use="required"></attribute>
    </complexType>

    <complexType name="subpopulationType">
      <attribute name="name" type="string" use="required"></attribute>
      <attribute name="groesse" type="int" default="0" use="optional"></attribute>
      <attribute name="sichtbar-infiziert" type="boolean" use="optional" default="false"></attribute>
      <attribute name="lebend" type="boolean" use="optional" default="true"></attribute>
    </complexType>

    <complexType name="uebergangType">
      <sequence>
        <element name="komponente" type="scfg:uebergangKomponenteType" maxOccurs="unbounded" minOccurs="1"></element>
      </sequence>
      <attribute name="von" type="string" use="required"></attribute>
      <attribute name="nach" type="string" use="required"></attribute>
    </complexType>

    <complexType name="uebergangKomponenteType">
      <sequence>
        <element name="reference" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      </sequence>
      <attribute name="scalar" type="float" default="1" use="optional"></attribute>
    </complexType>

    <complexType name="routenType">
      <sequence>
        <element name="route" type="scfg:routeType" maxOccurs="unbounded" minOccurs="0"></element>
      </sequence>
      <attribute name="flugverkehr" type="boolean" use="optional" default="false"></attribute>
      <attribute name="reisende-subpopulationen" type="string" use="required">
        <annotation>
          <documentation>comma separated</documentation>
        </annotation>
      </attribute>
    </complexType>

    <complexType name="routeType">
      <sequence>
        <element name="zuordnung" type="scfg:zuordnungType" minOccurs="0" maxOccurs="unbounded"></element>
      </sequence>
      <attribute name="von" type="string" use="required"></attribute>
      <attribute name="nach" type="string" use="required"></attribute>
      <attribute name="flug" type="boolean" default="false" use="optional"></attribute>
      <attribute name="anteil" type="float" use="optional" default="1"></attribute>
    </complexType>

    <complexType name="zuordnungType">
      <attribute name="vonSubpopulation" type="string" use="required"></attribute>
      <attribute name="nachSubpopulation" type="string" use="required"></attribute>
    </complexType>
</schema>

=== themetalone/WS1617-Masterarbeit/Simulation/resources/simulation-config/SIHFRD.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation batchgroesse="0" datenbank="target/SIHFRD/sihfrd" krankheit="1" xmlns="http://github.com/themetalone/simpleconfig"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://github.com/themetalone/simpleconfig ../../../PS-Utils/src/main/resources/configurator/xsd/Config.xsd "
  zeit="36">
  <populationen>
    <standard lebensstandard="0.0" migrationsanteil="0.0" name="" groesse="4108">
      <subpopulation groesse="11500000" name="S"/>
      <subpopulation name="I" groesse="4108" sichtbar-infiziert="true"/>
      <subpopulation name="H" sichtbar-infiziert="true"/>
      <subpopulation name="R"></subpopulation>
      <subpopulation name="F" lebend="false"/>
      <subpopulation name="D" lebend="false"/>

      <uebergang von="S" nach="I">
        <komponente scalar="2.18">
          <reference>I</reference>
        </komponente>
        <komponente scalar="0.2">
          <reference>F</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="H">
        <komponente scalar="0.7">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="R">
        <komponente scalar="0.15">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="F">
        <komponente scalar="0.15">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="H" nach="R">
        <komponente scalar="0.6">
          <reference>H</reference>
        </komponente>
      </uebergang>
      <uebergang von="H" nach="D">
        <komponente scalar="0.4">
          <reference>H</reference>
        </komponente>
      </uebergang>
      <uebergang von="F" nach="D">
        <komponente scalar="1">
          <reference>F</reference>
        </komponente>
      </uebergang>
    </standard>
    <population name="A" lebensstandard="1" migrationsanteil="0"/>
  </populationen>
  <routen flugverkehr="false" reisende-subpopulationen="S"/>
</simulation>

=== themetalone/WS1617-Masterarbeit/Simulation/resources/simulation-config/SEIHFRD_5P_10201496.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation batchgroesse="0" datenbank="target/SEIHFRD_5P_10201496/SEIHFRD_5P_10201496" krankheit="1"
  xmlns="http://github.com/themetalone/simpleconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://github.com/themetalone/simpleconfig ../../../PS-Utils/src/main/resources/configurator/xsd/Config.xsd "
  zeit="36">
  <!-- 5P_10201396 meint: 5 Populationen mit bidirektionaler Adjazenzmatrix, deren binäre Darstellung von links nach rechts und oben nach unten [10201396]_10 ergibt-->
  <!-- ABCDE -->
  <!-- Ax1001 -->
  <!-- B x111 -->
  <!-- C x10 -->
  <!-- D x0 -->
  <!-- E x -->
  <!-- 10201396 ergibt sich aus der Binärdarstellung der Matrixeinträge von links nach rechts und von oben nach unten. -->
  <populationen>
    <standard lebensstandard="0.0" migrationsanteil="0.0" name="" groesse="4108">
      <subpopulation groesse="11500000" name="S"/>
      <subpopulation name="E" groesse="4108"/>
      <subpopulation name="I" sichtbar-infiziert="true"/>
      <subpopulation name="H" sichtbar-infiziert="true"/>
      <subpopulation name="R"/>
      <subpopulation name="F" lebend="false"/>
      <subpopulation name="D" lebend="false"/>

      <uebergang von="S" nach="E">
        <komponente scalar="2.18">
          <reference>E</reference>
        </komponente>
        <komponente scalar="2.18">
          <reference>I</reference>
        </komponente>
        <komponente scalar="0.2">
          <reference>F</reference>
        </komponente>
      </uebergang>
      <uebergang von="E" nach="I">
        <komponente scalar="0.8">
          <reference>E</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="H">
        <komponente scalar="0.7">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="R">
        <komponente scalar="0.15">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="F">
        <komponente scalar="0.15">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="H" nach="R">
        <komponente scalar="0.6">
          <reference>H</reference>
        </komponente>
      </uebergang>
      <uebergang von="H" nach="D">
        <komponente scalar="0.4">
          <reference>H</reference>
        </komponente>
      </uebergang>
      <uebergang von="F" nach="D">
        <komponente scalar="1">
          <reference>F</reference>
        </komponente>
      </uebergang>
    </standard>
    <population name="A" lebensstandard="1" migrationsanteil="0.1"/>
    <population name="B" lebensstandard="1" migrationsanteil="0.1"/>
    <population name="C" lebensstandard="1" migrationsanteil="0.1"/>
    <population name="D" lebensstandard="1" migrationsanteil="0.1"/>
    <population name="E" lebensstandard="1" migrationsanteil="0.1"/>
  </populationen>
  <routen flugverkehr="false" reisende-subpopulationen="S,E">
    <route von="A" nach="B"/>
    <route von="A" nach="E"/>
    <route von="B" nach="A"/>
    <route von="B" nach="C"/>
    <route von="B" nach="D"/>
    <route von="B" nach="E"/>
    <route von="C" nach="B"/>
    <route von="C" nach="D"/>
    <route von="D" nach="B"/>
    <route von="D" nach="C"/>
    <route von="E" nach="A"/>
    <route von="E" nach="B"/>
  </routen>
</simulation>

=== themetalone/WS1617-Masterarbeit/Simulation/resources/simulation-config/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation batchgroesse="0" datenbank="" krankheit="0.0" xmlns="http://github.com/themetalone/simpleconfig"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://github.com/themetalone/simpleconfig ../../../PS-Utils/src/main/resources/configurator/xsd/Config.xsd "
  zeit="0">
  <populationen>
    <standard lebensstandard="0.0" migrationsanteil="0.0" name="">
      <subpopulation groesse="10000" name="S"/>
      <subpopulation groesse="5" name="E"/>
      <subpopulation name="I" sichtbar-infiziert="true"/>
      <subpopulation name="R"/>
      <subpopulation name="D" lebend="false"/>

      <uebergang von="S" nach="E">
        <komponente scalar="0.01">
          <reference>E</reference>
        </komponente>
        <komponente scalar="0.01">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="E" nach="I">
        <komponente>
          <reference>E</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="D">
        <komponente scalar="0.1">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="R">
        <komponente scalar="0.9">
          <reference>I</reference>
        </komponente>
      </uebergang>
    </standard>
    <population name="A" lebensstandard="1" migrationsanteil="0.05"/>
    <population name="B" lebensstandard="1" migrationsanteil="0.02"/>
    <population name="C" lebensstandard="0.5" migrationsanteil="0.1"/>
  </populationen>
  <routen flugverkehr="true" reisende-subpopulationen="S,E">
    <route von="A" nach="B" anteil="0.5"/>
    <route von="B" nach="A" anteil="0.3"/>
    <route von="B" nach="C" anteil="0.2"/>
    <route von="C" nach="B" anteil="0.6"/>
  </routen>
</simulation>

=== themetalone/WS1617-Masterarbeit/Simulation/resources/simulation-config/Model_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation batchgroesse="0" datenbank="target/SEIHFRD_5P_10201496/SEIHFRD_5P_10201496" krankheit="1"
  xmlns="http://github.com/themetalone/simpleconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://github.com/themetalone/simpleconfig ../../../PS-Utils/src/main/resources/configurator/xsd/Config.xsd "
  zeit="36">
  <!-- D
    |\
    A-B-C
    \|
    E
    Mit Infizierten zu Beginn nur in C. A verhaengt eine Quarantaene auf Einreisende. Diese laesst nur 1% Infizierte durch.
    Ansteckung in der Q ist nicht moeglich
  -->
  <populationen>
    <standard name="">
      <subpopulation groesse="11500000" name="S"/>
      <subpopulation name="E"/>
      <subpopulation name="I" sichtbar-infiziert="true"/>
      <subpopulation name="H" sichtbar-infiziert="true"/>
      <subpopulation name="R"/>
      <subpopulation name="F" lebend="false"/>
      <subpopulation name="D" lebend="false"/>

      <uebergang von="S" nach="E">
        <komponente scalar="2.18">
          <reference>E</reference>
        </komponente>
        <komponente scalar="2.18">
          <reference>I</reference>
        </komponente>
        <komponente scalar="0.2">
          <reference>F</reference>
        </komponente>
      </uebergang>
      <uebergang von="E" nach="I">
        <komponente scalar="1">
          <reference>E</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="H">
        <komponente scalar="0.7">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="R">
        <komponente scalar="0.09">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="F">
        <komponente scalar="0.21">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="H" nach="R">
        <komponente scalar="0.6">
          <reference>H</reference>
        </komponente>
      </uebergang>
      <uebergang von="H" nach="D">
        <komponente scalar="0.4">
          <reference>H</reference>
        </komponente>
      </uebergang>
      <uebergang von="F" nach="D">
        <komponente scalar="1">
          <reference>F</reference>
        </komponente>
      </uebergang>
    </standard>
    <population name="A" lebensstandard="2" migrationsanteil="0.1">
      <subpopulation name="Q"/>
      <uebergang von="E" nach="I">
        <komponente scalar="0.9">
          <reference>E</reference>
        </komponente>
      </uebergang>
      <uebergang von="Q" nach="E">
        <komponente scalar="0.01">
          <reference>Q</reference>
        </komponente>
      </uebergang>
      <uebergang von="Q" nach="H">
        <komponente scalar="0.99">
          <reference>Q</reference>
        </komponente>
      </uebergang>
    </population>
    <population name="B" lebensstandard="1" migrationsanteil="0.3">
      <uebergang von="E" nach="I">
        <komponente scalar="0.7">
          <reference>E</reference>
        </komponente>
      </uebergang>
    </population>
    <population name="C" lebensstandard="1" migrationsanteil="0.1">
      <subpopulation name="E" groesse="4100"/>
      <uebergang von="E" nach="I">
        <komponente scalar="0.9">
          <reference>E</reference>
        </komponente>
      </uebergang>
    </population>
    <population name="D" lebensstandard="2" migrationsanteil="0.1">
      <uebergang von="E" nach="I">
        <komponente scalar="0.9">
          <reference>E</reference>
        </komponente>
      </uebergang>
    </population>
    <population name="E" lebensstandard="1" migrationsanteil="0.1">
      <uebergang von="E" nach="I">
        <komponente scalar="0.9">
          <reference>E</reference>
        </komponente>
      </uebergang>
    </population>
  </populationen>
  <routen reisende-subpopulationen="S,E">
    <route von="A" nach="B"/>
    <route von="A" nach="E"/>
    <route von="B" nach="A">
      <zuordnung vonSubpopulation="S" nachSubpopulation="S"/>
      <zuordnung vonSubpopulation="E" nachSubpopulation="Q"/>
    </route>
    <route von="B" nach="C"/>
    <route von="B" nach="D"/>
    <route von="B" nach="E"/>
    <route von="C" nach="B"/>
    <route von="C" nach="D"/>
    <route von="D" nach="B"/>
    <route von="D" nach="C"/>
    <route von="E" nach="A">
      <zuordnung vonSubpopulation="S" nachSubpopulation="S"/>
      <zuordnung vonSubpopulation="E" nachSubpopulation="Q"/>
    </route>
    <route von="E" nach="B"/>
  </routen>
</simulation>

=== themetalone/WS1617-Masterarbeit/Simulation/PS-Utils/src/main/resources/configurator/configurations/simpleSystemTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation batchgroesse="1000" datenbank="simpleSystemTest/simpleSystemTest" krankheit="1"
  xmlns="http://github.com/themetalone/simpleconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://github.com/themetalone/simpleconfig ../xsd/Config.xsd " zeit="500">
  <populationen>
    <standard lebensstandard="1" migrationsanteil="0.1" name="standard">
      <subpopulation groesse="1000" lebend="true" name="S" sichtbar-infiziert="false"/>
      <subpopulation groesse="10" lebend="true" name="E" sichtbar-infiziert="false"/>
      <subpopulation groesse="0" lebend="true" name="I" sichtbar-infiziert="true"/>
      <subpopulation groesse="0" lebend="false" name="R" sichtbar-infiziert="false"/>
      <uebergang von="S" nach="E">
        <komponente scalar="2.18">
          <reference>E</reference>
        </komponente>
        <komponente scalar="2.18">
          <reference>I</reference>
        </komponente>
      </uebergang>
      <uebergang von="E" nach="I">
        <komponente scalar="0.8">
          <reference>E</reference>
        </komponente>
      </uebergang>
      <uebergang von="I" nach="R">
        <komponente scalar="0.7">
          <reference>I</reference>
        </komponente>
      </uebergang>
    </standard>
    <population name="A" lebensstandard="0.5" migrationsanteil="0.5"/>
    <population name="B" lebensstandard="1" migrationsanteil="0.1"/>
    <population name="C" lebensstandard="0.25" migrationsanteil="0.25"/>
    <population name="D" lebensstandard="1" migrationsanteil="0.1"/>
  </populationen>
  <routen flugverkehr="false" reisende-subpopulationen="S,E">
    <route von="A" nach="B"/>
    <route von="A" nach="C"/>
    <route von="B" nach="A"/>
    <route von="B" nach="D"/>
    <route von="C" nach="A"/>
    <route von="C" nach="D"/>
    <route von="D" nach="B"/>
    <route von="D" nach="C"/>
  </routen>
</simulation>

=== themetalone/WS1617-Masterarbeit/travis/Pandemic Simulation/config/Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation batchgroesse="0" datenbank="data/gtk" krankheit="1.0" xmlns="http://github.com/themetalone/simpleconfig"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://github.com/themetalone/simpleconfig ../../../PS-Utils/src/main/resources/configurator/xsd/Config.xsd "
  zeit="36">
  <populationen>
    <standard name="">
      <subpopulation groesse="11500000" name="G"/>
      <subpopulation groesse="4108" name="K" sichtbar-infiziert="true"/>
      <subpopulation name="T" lebend="false"/>

      <uebergang von="G" nach="K">
        <komponente scalar="2.18">
          <reference>K</reference>
        </komponente>
      </uebergang>
      <uebergang von="K" nach="G">
        <komponente scalar="0.5">
          <reference>K</reference>
        </komponente>
      </uebergang>
      <uebergang von="K" nach="T">
        <komponente scalar="0.5">
          <reference>K</reference>
        </komponente>
      </uebergang>
    </standard>
    <population name="A" />
  </populationen>
  <routen reisende-subpopulationen="S"/>
</simulation>
